"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./_components/SideBar";
import { useContext, useState } from "react";
import Login from "./_components/Login";
import UserProvider, { UserContext } from "./_context/userContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const backend_url = process.env.NEXT_PUBLIC_BACKEND_URL;
export const currency = "$";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <ToastContainer />
          <div className="flex items-start">
            <SideBar />
            <div className="bg-blue-50 w-full min-h-screen">{children}</div>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
